# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.ForeignKey(db_column='tipo_gasto_id', on_delete=django.db.models.deletion.CASCADE, to='controle.TipoGasto'),
        ),
    ]
